# ============================================================
#                   Nocturne — Configuration
# ============================================================

general:
  debug: false
  world: world

# ============================================================
# Phases
# ============================================================
phases:
  gameplay:
    min_duration: 10
    max_duration: 20
  vote:
    min_duration: 10
    max_duration: 10

# ============================================================
# Mécaniques
# ============================================================
mechanics:
  anonymity:
    hide_skins: true
    hide_nametags: true
    default_skin: steve

  spectral_arrows:
    default_count: 1
    redeem_if_miss: true

  elimination:
    reveal_role_on_death: false
    teleport_spectators: false
    spectator_location:
      x: 0
      y: 100
      z: 0

vote_tables:
  - "45, 103, -217"
  - "47, 103, -219"
  # Exemple :
  # vote_tables:
  #   - "0, 64, 0"
  #   - "5, 64, 0"

# ============================================================
# Cooldowns (secondes)
# ============================================================
cooldowns:
  poudre_cheminee: 5

starting_cooldowns:
  eclaircissement: 10
  embrasement: 10
  etouffement: 10
  apeliote: 10
  boree: 10
  lips: 10
  notos: 10
  sciron: 10
  polarisation: 10


# ============================================================
# Capacités
# ============================================================
abilities:
  double_swap:
    enabled: true
    max_delay_ms: 200

  capacity:
    rayonnement:
      radius: 10.0
      min_exposure_seconds: 10
      show_value: false

    zephyr:
      radius: 45.0
      only_not_protected: true

    notos:
      cooldown: 0
      show_protected_count: false
      cancel_if_before: false

    euros:
      self_protect_if_not_marked: true

    caecias:
      radius: 10
      
    sciron:
      cooldown: 3
      maxUsePerRound: -1

    polarisation:
      cooldown: 3
      min_decoy: 0
      max_decoy: 2

    incandescence:
      targets:
        - ""

    corrosion:
      negative_weight: -2
      negative_color: [85,255, 85]
      positive_weight: 2
      positive_color: [255,85, 85]

  effect:


  curse:
    murmuration:
      radius: 10

    amnesia:
      targets:
        - "BATON"
        - "AUTAN"
        - "CALCINE"
        - "TORCHE"

# ============================================================
# Messages
# ============================================================
messages:
  prefix: "§8[§eNocturne§8]§r "

# ============================================================
# UI
# ============================================================
ui:
  bossbar:
    enabled: true
    color_gameplay: BLUE
    color_vote: PINK

  actionbar:
    enabled: true

  sounds:
    enabled: true
    game_start: "entity.player.levelup"
    phase_change: "block.note_block.pling"
    elimination: "entity.lightning_bolt.thunder"
    ability_used: "block.note_block.hat"
    vote_cast: "entity.experience_orb.pickup"